import { Events } from "../core/Events.js";

export default class Inspector {
  constructor(element, eventBus) {
    this.element = element;
    this.eventBus = eventBus;
    this.model = null;
    this.selectedComponentId = null;
    eventBus.on(Events.DEVICE_MODEL_READY, this.onModelReady.bind(this));
    eventBus.on(Events.SELECTION_CHANGED, this.onSelectionChanged.bind(this));
    eventBus.on(Events.WORKING_COPY_CHANGED, this.onWorkingCopyChanged.bind(this));
    eventBus.on(Events.RUNTIME_CHANGED, this.onRuntimeChanged.bind(this));
  }
  onModelReady(model) { this.model = model; this.render(); }
  onSelectionChanged(id) { this.selectedComponentId = id; this.render(); }
  onWorkingCopyChanged() { this.syncColorInputs(); this.updateLedPreview(); this.syncColorWheel(); }
  onRuntimeChanged(p = {}) { if (p.componentId !== this.selectedComponentId) return; const e = this.element.querySelector("[data-inspector-runtime-value]"); if (e) e.textContent = p.value ?? "—"; }
  render() {
    if (!this.model || !this.selectedComponentId) { this.element.innerHTML = `<div class="inspector-empty"><p>No component selected.</p><span>Select a control on the device to edit its MIDI assignment.</span></div>`; return; }
    const c = this.model.getComponent(this.selectedComponentId), cfg = this.model.getComponentConfiguration(this.selectedComponentId) || {};
    if (!c) { this.element.innerHTML = `<div class="inspector-empty">The selected component is not available.</div>`; return; }
    const led = cfg.led || {}, rgb = led.color || { r: 255, g: 255, b: 255 }, type = c.type === "button" || c.type === "switch" ? "Button" : c.type === "fader" ? "Fader" : c.type === "knob" ? "Potentiometer" : c.type;
    this.element.innerHTML = `<section class="inspector-content"><div class="inspector-title"><div><span class="section-label">${type.toUpperCase()}</span><h2>${c.label}</h2></div><span class="inspector-id">${c.id}</span></div><div class="inspector-section"><div class="section-label">MIDI</div><div class="inspector-field"><label>Message</label><select id="message-type"><option value="cc" ${cfg.messageType !== "note" ? "selected" : ""}>Control Change</option><option value="note" ${cfg.messageType === "note" ? "selected" : ""}>Note</option></select></div><div class="inspector-grid"><div class="inspector-field"><label>Channel</label><input id="midi-channel" type="number" min="1" max="16" value="${cfg.channel ?? 1}"></div><div class="inspector-field"><label>Number</label><input id="midi-number" type="number" min="0" max="127" value="${cfg.number ?? 0}"></div></div>${type === "Button" ? `<div class="inspector-field"><label>Button mode</label><select id="button-mode"><option value="momentary" ${(cfg.mode ?? cfg.buttonMode) === "momentary" ? "selected" : ""}>Momentary</option><option value="toggle" ${(cfg.mode ?? cfg.buttonMode) === "toggle" ? "selected" : ""}>Permanent / Toggle</option></select></div>` : ""}</div><div class="inspector-section inspector-led"><div class="inspector-section-heading"><span class="section-label">LED</span><span>${c.led?.id ?? "RGB"}</span></div><div class="inspector-field"><label>Mode</label><select id="led-mode"><option value="static" ${led.mode === "static" ? "selected" : ""}>Static</option><option value="off" ${led.mode === "off" ? "selected" : ""}>Off</option><option value="runtime" ${led.mode === "runtime" ? "selected" : ""}>Runtime</option></select></div><div class="led-picker"><canvas id="led-color-wheel" width="220" height="220" aria-label="RGB color wheel"></canvas><div class="led-picker__side"><div class="led-preview" data-led-preview></div><div class="led-color-row"><div class="inspector-field"><label>R</label><input id="led-r" type="number" min="0" max="255" value="${rgb.r}"></div><div class="inspector-field"><label>G</label><input id="led-g" type="number" min="0" max="255" value="${rgb.g}"></div><div class="inspector-field"><label>B</label><input id="led-b" type="number" min="0" max="255" value="${rgb.b}"></div></div></div></div><div class="inspector-field"><label>Brightness <span id="led-brightness-value">${led.brightness ?? 100}%</span></label><input id="led-brightness" type="range" min="0" max="100" value="${led.brightness ?? 100}"></div></div><div class="inspector-runtime"><span>Runtime value</span><strong data-inspector-runtime-value>${this.model.getComponentRuntime(this.selectedComponentId) ?? "—"}</strong></div></section>`;
    this.bindEvents(); this.drawColorWheel(); this.syncColorInputs(); this.syncColorWheel(); this.updateLedPreview();
  }
  bindEvents() {
    this.element.querySelector("#message-type")?.addEventListener("change", e => this.update({ messageType: e.target.value }));
    this.element.querySelector("#midi-channel")?.addEventListener("change", e => { const v = this.clamp(e.target.value, 1, 16); e.target.value = v; this.update({ channel: v }); });
    this.element.querySelector("#midi-number")?.addEventListener("change", e => { const v = this.clamp(e.target.value, 0, 127); e.target.value = v; this.update({ number: v }); });
    this.element.querySelector("#button-mode")?.addEventListener("change", e => this.update({ mode: e.target.value, buttonMode: e.target.value }));
    this.element.querySelector("#led-mode")?.addEventListener("change", e => this.updateLed({ mode: e.target.value }));
    ["r", "g", "b"].forEach(k => this.element.querySelector(`#led-${k}`)?.addEventListener("input", e => { const v = this.clamp(e.target.value, 0, 255); e.target.value = v; this.updateLed({ color: this.currentColor(k, v) }); }));
    this.element.querySelector("#led-brightness")?.addEventListener("input", e => { const v = Number(e.target.value); const label = this.element.querySelector("#led-brightness-value"); if (label) label.textContent = `${v}%`; this.updateLed({ brightness: v }); });
    const wheel = this.element.querySelector("#led-color-wheel");
    if (wheel) { let active = false; const pick = e => { const r = wheel.getBoundingClientRect(); this.pickWheelColor(e.clientX-r.left,e.clientY-r.top,wheel.width,wheel.height); }; wheel.addEventListener("pointerdown",e=>{active=true;wheel.setPointerCapture?.(e.pointerId);pick(e)}); wheel.addEventListener("pointermove",e=>{if(active)pick(e)}); const stop=e=>{active=false;wheel.releasePointerCapture?.(e.pointerId)}; wheel.addEventListener("pointerup",stop); wheel.addEventListener("pointercancel",stop); }
  }
  syncColorInputs() { const cfg=this.model?.getComponentConfiguration(this.selectedComponentId)||{}, c=cfg.led?.color||{r:255,g:255,b:255}; ["r","g","b"].forEach(k=>{const el=this.element.querySelector(`#led-${k}`);if(el)el.value=c[k];}); }
  drawColorWheel() { const canvas=this.element.querySelector("#led-color-wheel");if(!canvas)return;const ctx=canvas.getContext("2d"),size=canvas.width,cx=size/2,cy=size/2,radius=size/2-4,image=ctx.createImageData(size,size);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy),i=(y*size+x)*4;if(d>radius){image.data[i+3]=0;continue}const h=(Math.atan2(dy,dx)*180/Math.PI+360)%360,s=d/radius,hh=h/60,c=s,x1=c*(1-Math.abs(hh%2-1));let r=0,g=0,b=0;if(hh<1)[r,g,b]=[c,x1,0];else if(hh<2)[r,g,b]=[x1,c,0];else if(hh<3)[r,g,b]=[0,c,x1];else if(hh<4)[r,g,b]=[0,x1,c];else if(hh<5)[r,g,b]=[x1,0,c];else[r,g,b]=[c,0,x1];image.data[i]=Math.round((r+1-c)*255);image.data[i+1]=Math.round((g+1-c)*255);image.data[i+2]=Math.round((b+1-c)*255);image.data[i+3]=255;}ctx.putImageData(image,0,0);}
  pickWheelColor(x,y,width,height){const cx=width/2,cy=height/2,radius=Math.min(width,height)/2-4,dx=x-cx,dy=y-cy,distance=Math.hypot(dx,dy);if(distance>radius)return;const h=(Math.atan2(dy,dx)*180/Math.PI+360)%360,s=distance/radius,hh=h/60,c=s,x1=c*(1-Math.abs(hh%2-1));let r=0,g=0,b=0;if(hh<1)[r,g,b]=[c,x1,0];else if(hh<2)[r,g,b]=[x1,c,0];else if(hh<3)[r,g,b]=[0,c,x1];else if(hh<4)[r,g,b]=[0,x1,c];else if(hh<5)[r,g,b]=[x1,0,c];else[r,g,b]=[c,0,x1];this.updateLed({color:{r:Math.round((r+1-c)*255),g:Math.round((g+1-c)*255),b:Math.round((b+1-c)*255)}});}
  syncColorWheel(){const canvas=this.element.querySelector("#led-color-wheel");if(!canvas)return;const cfg=this.model?.getComponentConfiguration(this.selectedComponentId)||{},c=cfg.led?.color||{r:255,g:255,b:255},max=Math.max(c.r,c.g,c.b),min=Math.min(c.r,c.g,c.b),delta=max-min;let h=0;if(delta){if(max===c.r)h=60*(((c.g-c.b)/delta)%6);else if(max===c.g)h=60*((c.b-c.r)/delta+2);else h=60*((c.r-c.g)/delta+4);if(h<0)h+=360;}const s=max?delta/max:0,r=Math.min(canvas.width,canvas.height)/2-4,x=canvas.width/2+r*s*Math.cos(h*Math.PI/180),y=canvas.height/2+r*s*Math.sin(h*Math.PI/180),ctx=canvas.getContext("2d");this.drawColorWheel();ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.strokeStyle="rgba(0,0,0,.7)";ctx.lineWidth=1;ctx.stroke();}
  currentColor(channel,value){const cfg=this.model.getComponentConfiguration(this.selectedComponentId)||{},color={...(cfg.led?.color||{r:255,g:255,b:255})};color[channel]=value;return color;}
  updateLed(patch){const cfg=this.model.getComponentConfiguration(this.selectedComponentId)||{},led={...(cfg.led||{}),...patch};this.update({led});this.updateLedPreview(led);this.syncColorInputs();this.syncColorWheel();}
  updateLedPreview(led=null){if(!led){const cfg=this.model?.getComponentConfiguration(this.selectedComponentId)||{};led=cfg.led||{};}const c=led.color||{r:255,g:255,b:255},brightness=Number(led.brightness??100)/100,p=this.element.querySelector("[data-led-preview]");if(p){p.style.background=`rgb(${c.r},${c.g},${c.b})`;p.style.opacity=brightness;p.style.boxShadow=`0 0 ${8+12*brightness}px rgb(${c.r},${c.g},${c.b})`;}}
  update(patch){this.model.updateComponentConfiguration(this.selectedComponentId,patch)}
  clamp(v,min,max){const n=Number.parseInt(v,10);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):min;}
}
