import { Events } from "../core/Events.js";

export default class Workspace {
    constructor(element, eventBus, selectionManager) {
        this.element=element; this.eventBus=eventBus; this.selectionManager=selectionManager; this.model=null; this.selectedComponentId=null; this.runtimeValues={};
        eventBus.on(Events.DEVICE_MODEL_READY,this.onModelReady.bind(this)); eventBus.on(Events.SELECTION_CHANGED,this.onSelectionChanged.bind(this)); eventBus.on(Events.RUNTIME_CHANGED,this.onRuntimeChanged.bind(this)); eventBus.on(Events.WORKING_COPY_CHANGED,this.onWorkingCopyChanged.bind(this));
    }
    onModelReady(model){this.model=model;this.runtimeValues=model.runtime?.toJSON?.()??{};this.render();}
    onSelectionChanged(id){this.selectedComponentId=id;this.render();}
    onRuntimeChanged(p={}){if(!p.componentId)return;this.runtimeValues[p.componentId]=p.value;this.updateRuntimeVisual(p.componentId);}
    onWorkingCopyChanged(p={}){if(p.componentId)this.updateLedVisual(p.componentId);else this.render();}
    render(){
        if(!this.model?.hardware){this.element.innerHTML=`<div class="waiting">Waiting for a bipoLab device...</div>`;return;}
        const components=this.model.hardware.getComponents(),name=this.model.device.name,kind=components[0]?.type;
        const surfaceClass=kind==="fader"?"device-panel--faders":kind==="button"||kind==="switch"?"device-panel--buttons":"device-panel--knobs";
        const gridClass=kind==="fader"?"device-grid device-grid--faders":"device-grid device-grid--4x4";
        const label=kind==="knob"?"POTENTIOMETERS":kind==="button"||kind==="switch"?"BUTTONS":"FADERS";
        this.element.innerHTML=`<section class="device-workspace"><div class="device-panel ${surfaceClass}"><header class="device-panel__header"><div><span class="section-label">bipoLab engineering</span><h1>${name}</h1></div><span class="device-workspace__mode">CONFIGURATION · MOCK</span></header><div class="${gridClass}" aria-label="${name} controls">${components.map(c=>this.renderComponent(c)).join("")}</div><footer class="device-panel__footer"><span>${components.length} ${label}</span><span>${kind==="fader"?"4 × 1":"4 × 4"}</span></footer></div></section>`;
        this.bindComponentEvents();
    }
    renderComponent(component){
        const controllerSelected=component.id===this.selectedComponentId,ledId=`${component.id}-LED`,ledSelected=ledId===this.selectedComponentId,value=Math.round(this.getRuntimeValue(component.id));
        const cfg=this.model.getComponentConfiguration(component.id)??{},led=cfg.led??{id:ledId,mode:"static",color:{r:255,g:255,b:255},brightness:100},rgb=led.color??{r:255,g:255,b:255};
        const alpha=Math.max(0,Math.min(1,Number(led.brightness??100)/100)),ledStyle=`--led-r:${rgb.r};--led-g:${rgb.g};--led-b:${rgb.b};--led-a:${alpha}`;
        return `<div class="device-cell ${controllerSelected||ledSelected?"device-cell--selected":""}"><div class="device-control device-control--${component.type} ${controllerSelected?"device-control--selected":""}" data-component-id="${component.id}" tabindex="0" role="button" title="${component.label}" aria-label="Configure ${component.label}"><span class="device-control__visual" style="--runtime-value:${value}"></span><span class="device-control__led ${ledSelected?"device-control__led--selected":""}" data-led-component="${component.id}" data-led-id="${ledId}" style="${ledStyle}" title="Configure ${ledId}" role="button" tabindex="0" aria-label="Configure LED ${ledId}"></span><span class="device-control__label">${component.label}</span></div></div>`;
    }
    bindComponentEvents(){this.element.querySelectorAll("[data-component-id]").forEach(control=>{const id=control.dataset.componentId,component=this.model.getComponent(id),configuration=this.model.getComponentConfiguration(id)??{},isButton=component?.type==="switch"||component?.type==="button";control.addEventListener("click",e=>{if(e.target.closest("[data-led-id]"))return;this.selectionManager.select(id)});control.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&!e.target.closest("[data-led-id]")){e.preventDefault();this.selectionManager.select(id)}});if(component?.type==="knob"||component?.type==="fader"){let dragging=false,lastY=0;control.addEventListener("pointerdown",e=>{if(e.target.closest("[data-led-id]"))return;dragging=true;lastY=e.clientY;control.setPointerCapture?.(e.pointerId);e.preventDefault()});control.addEventListener("pointermove",e=>{if(!dragging)return;const d=lastY-e.clientY;lastY=e.clientY;this.setRuntimeValue(id,this.getRuntimeValue(id)+d*(component.type==="fader"?1.2:.8));e.preventDefault()});const stop=e=>{dragging=false;control.releasePointerCapture?.(e.pointerId)};control.addEventListener("pointerup",stop);control.addEventListener("pointercancel",stop)}if(isButton){const mode=configuration.mode??configuration.buttonMode??"momentary";if(mode==="toggle")control.addEventListener("click",e=>{if(e.target.closest("[data-led-id]"))return;this.setRuntimeValue(id,this.getRuntimeValue(id)>0?0:127)});else{control.addEventListener("pointerdown",e=>{if(e.target.closest("[data-led-id]"))return;this.setRuntimeValue(id,127);control.setPointerCapture?.(e.pointerId)});const release=e=>{if(e.target?.closest?.("[data-led-id]"))return;this.setRuntimeValue(id,0);control.releasePointerCapture?.(e.pointerId)};control.addEventListener("pointerup",release);control.addEventListener("pointercancel",release)}}});this.element.querySelectorAll("[data-led-id]").forEach(led=>{const id=led.dataset.ledId;led.addEventListener("click",e=>{e.stopPropagation();this.selectionManager.select(id)});led.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();e.stopPropagation();this.selectionManager.select(id)}});});}
    getRuntimeValue(id){return Number(this.runtimeValues[id]??0)}
    setRuntimeValue(id,value){const v=Math.round(Math.min(127,Math.max(0,Number(value)||0)));this.runtimeValues[id]=v;this.model?.setRuntimeValue(id,v)}
    updateRuntimeVisual(id){const c=this.element.querySelector(`[data-component-id="${id}"]`);if(!c)return;const v=this.getRuntimeValue(id);c.querySelector(".device-control__visual")?.style.setProperty("--runtime-value",v)}
    updateLedVisual(id){const c=this.element.querySelector(`[data-component-id="${id}"]`);if(!c)return;const cfg=this.model.getComponentConfiguration(id)??{},led=cfg.led??{},rgb=led.color??{r:255,g:255,b:255},alpha=Math.max(0,Math.min(1,Number(led.brightness??100)/100)),element=c.querySelector("[data-led-component]");if(!element)return;element.style.setProperty("--led-r",rgb.r);element.style.setProperty("--led-g",rgb.g);element.style.setProperty("--led-b",rgb.b);element.style.setProperty("--led-a",alpha);}
}
