import { Events } from "../core/Events.js";

export default class Workspace {
    constructor(element, eventBus, selectionManager) { this.element=element; this.eventBus=eventBus; this.selectionManager=selectionManager; this.model=null; this.selectedComponentId=null; this.runtimeValues={}; eventBus.on(Events.DEVICE_MODEL_READY,this.onModelReady.bind(this)); eventBus.on(Events.SELECTION_CHANGED,this.onSelectionChanged.bind(this)); eventBus.on(Events.RUNTIME_CHANGED,this.onRuntimeChanged.bind(this)); }
    onModelReady(model){this.model=model;this.runtimeValues=model.runtime?.toJSON?.()??{};this.render();}
    onSelectionChanged(id){this.selectedComponentId=id;this.render();}
    onRuntimeChanged(p={}){if(!p.componentId)return;this.runtimeValues[p.componentId]=p.value;this.updateRuntimeVisual(p.componentId);}
    render(){if(!this.model?.hardware){this.element.innerHTML=`<div class="waiting">Waiting for a bipoLab device...</div>`;return;}const components=this.model.hardware.getComponents(),name=this.model.device.name,kind=components[0]?.type,surfaceClass=kind==="fader"?"device-panel--faders":kind==="button"||kind==="switch"?"device-panel--buttons":"device-panel--knobs",gridClass=kind==="fader"?"device-grid device-grid--faders":"device-grid device-grid--4x4",label=kind==="knob"?"POTENTIOMETERS":kind==="button"||kind==="switch"?"BUTTONS":"FADERS";this.element.innerHTML=`<section class="device-workspace"><div class="device-panel ${surfaceClass}"><header class="device-panel__header"><div><span class="section-label">bipoLab engineering</span><h1>${name}</h1></div><span class="device-workspace__mode">CONFIGURATION · MOCK</span></header><div class="${gridClass}" aria-label="${name} controls">${components.map(c=>this.renderComponent(c)).join("")}</div><footer class="device-panel__footer"><span>${components.length} ${label}</span><span>${kind==="fader"?"4 × 1":"4 × 4"}</span></footer></div><p class="device-workspace__hint">Select a control to configure it. Use the control to test its runtime behavior.</p></section>`;this.bindComponentEvents();}
    renderComponent(component){const selected=component.id===this.selectedComponentId,led=component.led??{id:`${component.id}-LED`,mode:"static",color:{r:255,g:255,b:255},brightness:100},rgb=led.color??{r:255,g:255,b:255},alpha=Math.max(0,Math.min(1,Number(led.brightness??100)/100)),ledStyle=`--led-r:${rgb.r};--led-g:${rgb.g};--led-b:${rgb.b};--led-a:${alpha}`;return `<div class="device-cell ${selected?"device-cell--selected":""}"><button class="device-control device-control--${component.type}" data-component-id="${component.id}" type="button" title="${component.label}" aria-label="Configure ${component.label}"><span class="device-control__visual"></span><span class="device-control__led" style="${ledStyle}" title="${led.id}"></span><span class="device-control__label">${component.label}</span></button></div>`;}
    bindComponentEvents(){this.element.querySelectorAll("[data-component-id]").forEach(control=>{const id=control.dataset.componentId,component=this.model.getComponent(id),configuration=this.model.getComponentConfiguration(id)??{},isButton=component?.type==="switch"||component?.type==="button";control.addEventListener("click",()=>this.selectionManager.select(id));if(component?.type==="knob"||component?.type==="fader"){let dragging=false,lastY=0;control.addEventListener("pointerdown",e=>{dragging=true;lastY=e.clientY;control.setPointerCapture?.(e.pointerId);e.preventDefault();});control.addEventListener("pointermove",e=>{if(!dragging)return;const delta=lastY-e.clientY;lastY=e.clientY;this.setRuntimeValue(id,this.getRuntimeValue(id)+delta*(component.type==="fader"?1.2:0.8));e.preventDefault();});const stop=e=>{dragging=false;control.releasePointerCapture?.(e.pointerId);};control.addEventListener("pointerup",stop);control.addEventListener("pointercancel",stop);}if(isButton){const mode=configuration.mode??configuration.buttonMode??"momentary";if(mode==="toggle")control.addEventListener("click",()=>this.setRuntimeValue(id,this.getRuntimeValue(id)>0?0:127));else{control.addEventListener("pointerdown",e=>{this.setRuntimeValue(id,127);control.setPointerCapture?.(e.pointerId);});const release=e=>{this.setRuntimeValue(id,0);control.releasePointerCapture?.(e.pointerId);};control.addEventListener("pointerup",release);control.addEventListener("pointercancel",release);}}});}
    getRuntimeValue(id){return Number(this.runtimeValues[id]??0);}
    setRuntimeValue(id,value){const v=Math.round(Math.min(127,Math.max(0,Number(value)||0)));this.runtimeValues[id]=v;this.model?.setRuntimeValue(id,v);}
    updateRuntimeVisual(id){const control=this.element.querySelector(`[data-component-id="${id}"]`);if(!control)return;}
}
