import { Events } from "../core/Events.js";

/** Fixed visual representation of the emulated device. */
export default class Workspace {
    constructor(element, eventBus, selectionManager) { this.element=element; this.eventBus=eventBus; this.selectionManager=selectionManager; this.model=null; this.selectedComponentId=null; this.runtimeValues={}; this.eventBus.on(Events.DEVICE_MODEL_READY,this.onModelReady.bind(this)); this.eventBus.on(Events.SELECTION_CHANGED,this.onSelectionChanged.bind(this)); this.eventBus.on(Events.RUNTIME_CHANGED,this.onRuntimeChanged.bind(this)); }
    onModelReady(model){this.model=model;this.runtimeValues=model.runtime?.toJSON?.()??{};this.render();}
    onSelectionChanged(id){this.selectedComponentId=id;this.render();}
    onRuntimeChanged(p={}){if(!p.componentId)return;this.runtimeValues[p.componentId]=p.value;this.updateRuntimeVisual(p.componentId);}
    render(){
        if(!this.model?.hardware){this.element.innerHTML=`<div class="waiting">Waiting for a bipoLab device...</div>`;return;}
        const components=this.model.hardware.getComponents(),name=this.model.device.name,kind=components[0]?.type;
        const surfaceClass=kind==="fader"?"device-surface--faders":kind==="button"||kind==="switch"?"device-surface--buttons":"device-surface--knobs";
        this.element.innerHTML=`<section class="device-workspace"><div class="device-workspace__heading"><div><span class="section-label">DEVICE</span><h1>${name}</h1></div><span class="device-workspace__mode">CONFIGURATION · MOCK</span></div><div class="device-surface-wrap"><div class="device-surface ${surfaceClass}" aria-label="${name} device mock"><div class="device-surface__brand">bipoLab engineering</div><div class="device-surface__model">${name}</div>${components.map(c=>this.renderComponent(c)).join("")}</div></div><p class="device-workspace__hint">Select a control to configure it. Use the control to test its runtime behavior.</p></section>`;
        this.bindComponentEvents();
    }
    renderComponent(c){const selected=c.id===this.selectedComponentId,value=Math.round(this.getRuntimeValue(c.id));return `<button class="device-control device-control--${c.type} ${selected?"device-control--selected":""}" data-component-id="${c.id}" style="left:${c.position?.x??0}px;top:${c.position?.y??0}px" type="button" title="${c.label}" aria-label="Configure ${c.label}"><span class="device-control__visual" style="--runtime-value:${value}"></span><span class="device-control__label">${c.label}</span><span class="device-control__value" data-runtime-value="${c.id}">${value}</span></button>`;}
    bindComponentEvents(){this.element.querySelectorAll("[data-component-id]").forEach(control=>{const id=control.dataset.componentId,component=this.model.getComponent(id),configuration=this.model.getComponentConfiguration(id)??{},isButton=component?.type==="button"||component?.type==="switch";control.addEventListener("click",()=>this.selectionManager.select(id));if(component?.type==="knob"||component?.type==="fader"){let dragging=false,lastY=0;control.addEventListener("pointerdown",e=>{dragging=true;lastY=e.clientY;control.setPointerCapture?.(e.pointerId);e.preventDefault();});control.addEventListener("pointermove",e=>{if(!dragging)return;const delta=lastY-e.clientY;lastY=e.clientY;this.setRuntimeValue(id,this.getRuntimeValue(id)+delta*(component.type==="fader"?1.2:.8));e.preventDefault();});const stop=e=>{dragging=false;control.releasePointerCapture?.(e.pointerId);};control.addEventListener("pointerup",stop);control.addEventListener("pointercancel",stop);}if(isButton){const mode=configuration.mode??configuration.buttonMode??"momentary";if(mode==="toggle")control.addEventListener("click",()=>this.setRuntimeValue(id,this.getRuntimeValue(id)>0?0:127));else{control.addEventListener("pointerdown",e=>{this.setRuntimeValue(id,127);control.setPointerCapture?.(e.pointerId);});const release=e=>{this.setRuntimeValue(id,0);control.releasePointerCapture?.(e.pointerId);};control.addEventListener("pointerup",release);control.addEventListener("pointercancel",release);}}});}
    getRuntimeValue(id){return Number(this.runtimeValues[id]??0);}
    setRuntimeValue(id,value){const normalized=Math.round(Math.min(127,Math.max(0,Number(value)||0)));this.runtimeValues[id]=normalized;this.model?.setRuntimeValue(id,normalized);}
    updateRuntimeVisual(id){const control=this.element.querySelector(`[data-component-id="${id}"]`);if(!control)return;const value=this.getRuntimeValue(id);control.querySelector(".device-control__visual")?.style.setProperty("--runtime-value",value);const el=control.querySelector("[data-runtime-value]");if(el)el.textContent=value;}
}
